#!/usr/bin/python3

import subprocess
import datetime
from influxdb import InfluxDBClient

cmd = '/usr/bin/speedtest --simple --server 4207'
host = '<hostname>'
port = '8086'
user = 'admin'
password = '<password>'
dbname = 'collectd'
time = time = datetime.datetime.now() + datetime.timedelta(hours=7)

# run command, capture stdout & stderr, decode tuple byte list to tuple string list, split string by space
p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = p.communicate()
stdout_string = stdout.decode("utf8")
bandwidth = stdout_string.split()
# bandwidth should now have ping result in index 1, download in index 4, upload in index 7

# create connection to InfluxDB with pre-defined parameters. Do inserts for each value, tagging each one.
# use current time for value. inserting 3 tags at once goes against InfluxDB data structure
dbclient = InfluxDBClient(host, port, user, password, dbname)

json_body = [
{
    "measurement": "isp_bandwidth",
    "tags": {
        "type": "latency"
    },
    "time": time,
    "fields": {
        "value": float(bandwidth[1])

    }
}
]

dbclient.write_points(json_body)

json_body = [
{
    "measurement": "isp_bandwidth",
    "tags": {
        "type": "download"
    },
    "time": time,
    "fields": {
        "value": float(bandwidth[4])

    }
}
]

dbclient.write_points(json_body)

json_body = [
{
    "measurement": "isp_bandwidth",
    "tags": {
        "type": "upload"
    },
    "time": time,
    "fields": {
        "value": float(bandwidth[7])

    }
}
]

dbclient.write_points(json_body)
